<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../CDSI.Agent.Application/CDSI.Agent.Application.csproj" />
    <ProjectReference Include="../../CDSI.Agent.Core/CDSI.Agent.Core.csproj" />
    <ProjectReference Include="../../CDSI.Agent.Infrastructure/CDSI.Agent.Infrastructure.csproj" />
  </ItemGroup>
</Project>
